### ISSUE TITLE
Python package checklist

### ISSUE THREAD

**Issue by caesarw0** [UBC-MDS/sanityze#43]
Recall that each team member should write at least one function in R and one function in Python and unit tests for both functions.
Function assignment:
- Tony - cleanser
- Jonah - creditcardspotter
- Caesar - emailspotter

- [x] at least 3 unit tests for each function
- [x] document the test functions (with comments)
- [x] code passes the unit tests (please check git actions)
![image](https://user-images.githubusercontent.com/112133161/213884276-e5af1bf4-552c-418c-9d90-257b91aaa873.png)
![image](https://user-images.githubusercontent.com/112133161/213884282-8b3986ec-6000-4b11-b5f7-c864f2a37ce8.png)

- [x] able to install and use your Python package functions from GitHub

**Comment by caesarw0** [comment]
checked Python deliverables
