### ISSUE TITLE
milestone 3 Python package checklist

### ISSUE THREAD

**Issue by caesarw0** [UBC-MDS/sanityze#44]
Please check the following upon milestone 3 submission:
- [x] Documentation 
    - [x] Deployed by ReadTheDocs
    - [x] Render all docstring using the napolean Sphinx extnesion and readable on ReadTheDocs
    - [x] Include a demonstration of how to use each function in the package

- [x] GitHub actions workflows for CI-CD (modify the .github/workflows/ci-cd.yml)
    - [x] Correctly configured and runs the test suite and style checkers on pushes and pull requests on the **main** branch
    - [x] Deployed to TestPyPI and PyPI on pushes to main
    - [x] Expect that the workflow run completed succesfully

**Comment by tzoght** [comment]
I believe that these are all completed

**Comment by tzoght** [comment]
All work items listed above are completed.
