### ISSUE TITLE
Milestone 4 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/sanityze#53]
Congratulations on finishing milestone 4! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project.

RStudio

- [ ] Why are there still branches that exists that aren’t deleted if the package is finished? -1 Mechanics

- [ ] The link to the website created with pkgdown or it is not possible to be easily found for an user - -5 reasoning

- [ ] Project board Past due by 3 days, and still uncompleted -1 

Python

- [ ] Why are there still branches that exists that aren’t deleted if the package is finished? -1 Mechanics

- [ ] There aren't meaningful names for the branches. - mechanics -2 For example: add_document

We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.
